"""Resilient workflow orchestration.

Local processing is the system of record. Gemini is an optional enrichment.
An enrichment failure can never discard a successful local result.
"""
import json
from project_1_quality_8d.engine import build_8d
from project_3_low_code_agent.agent import triage
from shared.schemas import GeminiQualityReview, GeminiTriageReview

LOCAL_NOTICE = "Result generated by the local deterministic engine. Gemini AI was not used."
FALLBACK_NOTICE = "Result generated successfully by the local deterministic engine. The optional Gemini AI enhancement was unavailable and was not used."
GEMINI_NOTICE = "Result generated by the local deterministic engine and enhanced with an optional Gemini AI review. Human validation remains required."

def _base_provenance(profile, engine, requested):
    return {"profile":profile,"local_engine":engine,"local_engine_status":"success",
            "result_source":"local","gemini_requested":bool(requested),"gemini_used":False,
            "gemini_status":"not_requested" if not requested else "pending","user_notice":LOCAL_NOTICE}

def run_quality(data, profile="local", use_gemini=False, structured_generator=None, model=None):
    result=build_8d(data)
    result["provenance"]=_base_provenance(profile,"rules-v2",use_gemini)
    if use_gemini:
        try:
            if structured_generator is None: raise RuntimeError("Gemini generator is unavailable")
            result["gemini_review"]=structured_generator(
                "You are a cautious manufacturing quality copilot. Separate facts from hypotheses.",
                json.dumps(result),GeminiQualityReview)
            result["provenance"].update({"result_source":"local_plus_gemini","gemini_used":True,"gemini_status":"success","gemini_model":model,"user_notice":GEMINI_NOTICE})
        except Exception as exc:
            result["gemini_review"]={"status":"UNAVAILABLE","message":FALLBACK_NOTICE}
            result["provenance"].update({"gemini_used":False,"gemini_status":"failed","gemini_error_type":type(exc).__name__,"user_notice":FALLBACK_NOTICE})
    return result

def run_fault(data, profile="local", use_gemini=False, structured_generator=None, model=None):
    result=triage(data)
    result["provenance"]=_base_provenance(profile,"transparent-rules-v2",use_gemini)
    if use_gemini:
        try:
            if structured_generator is None: raise RuntimeError("Gemini generator is unavailable")
            result["gemini_review"]=structured_generator(
                "You are a safety-conscious manufacturing triage copilot. Never recommend bypassing safeguards.",
                json.dumps(result),GeminiTriageReview)
            result["provenance"].update({"result_source":"local_plus_gemini","gemini_used":True,"gemini_status":"success","gemini_model":model,"user_notice":GEMINI_NOTICE})
        except Exception as exc:
            result["gemini_review"]={"status":"UNAVAILABLE","message":FALLBACK_NOTICE}
            result["provenance"].update({"gemini_used":False,"gemini_status":"failed","gemini_error_type":type(exc).__name__,"user_notice":FALLBACK_NOTICE})
    return result

def run_knowledge(query, retriever, profile="local", use_gemini=False, answer_generator=None):
    hits=retriever.search(query,top_k=4)
    provenance={"profile":profile,"retrieval_engine":"tfidf-v1","retrieval_status":"success","result_source":"local",
                "gemini_requested":bool(use_gemini),"gemini_used":False,"gemini_status":"not_requested" if not use_gemini else "pending","user_notice":LOCAL_NOTICE}
    if not hits:
        provenance.update({"gemini_status":"not_requested","user_notice":"No supporting local evidence was found. Gemini AI was not used."})
        return {"question":query,"answer":"No supporting evidence was found in the current knowledge base.","matches":[],"status":"NO_EVIDENCE","provenance":provenance}
    local_answer="Evidence summary: "+" ".join(h["text"] for h in hits)
    answer=local_answer
    if use_gemini:
        evidence="\n\n".join(f"[{h['source']}#chunk-{h['chunk']}] {h['text']}" for h in hits)
        try:
            if answer_generator is None: raise RuntimeError("Gemini answer generator is unavailable")
            answer=answer_generator(query,evidence)
            provenance.update({"result_source":"local_retrieval_plus_gemini","gemini_used":True,"gemini_status":"success","user_notice":GEMINI_NOTICE})
        except Exception as exc:
            provenance.update({"gemini_used":False,"gemini_status":"failed","gemini_error_type":type(exc).__name__,"user_notice":FALLBACK_NOTICE})
    return {"question":query,"answer":answer,"matches":hits,"status":"EVIDENCE_BACKED_DRAFT","provenance":provenance}
